# Generated by Django 6.0.6 on 2026-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logo',
        ),
        migrations.AddField(
            model_name='client',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
