# Generated by Django 6.0.6 on 2026-07-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bookitem_quantity_inventorymovement_quantity_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='inventory.hub'),
        ),
        migrations.AddField(
            model_name='salelog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salelog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of book copies purchased in this single transaction line'),
        ),
        migrations.AlterField(
            model_name='salelog',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, help_text='The total amount paid for this transaction row', max_digits=10),
        ),
    ]
