# Generated by Django 6.0.6 on 2026-08-02 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorymovement_product'),
        ('sales', '0002_salelog_hub_salelog_product_salelog_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelog',
            name='book_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bookitem'),
        ),
    ]
