from rest_framework import serializers

from .models import SaleLog


class SaleLogSerializer(serializers.ModelSerializer):
    """
    Serialize a completed book sale.

    SaleLog links the sold physical copy to the salesperson and stores the final
    sale price. The sold_at timestamp is generated by the database model.
    """

    class Meta:
        model = SaleLog
        fields = ["id", "book_item", "salesperson", "sale_price", "sold_at"]
        read_only_fields = ["id", "sold_at"]
