from rest_framework import serializers

from .models import SaleLog


class SaleLogSerializer(serializers.ModelSerializer):
    """
    Serialize a completed book sale.

    SaleLog links the sold physical copy to the salesperson and stores the final
    sale price. The sold_at timestamp is generated by the database model.
    """

    product_title = serializers.ReadOnlyField(source="book_item.product.title")
    book_serial = serializers.ReadOnlyField(source="book_item.serial_number")
    salesperson_name = serializers.ReadOnlyField(source="salesperson.username")

    class Meta:
        model = SaleLog
        fields = ["id", "book_item", "book_serial", "product_title", "salesperson", "salesperson_name", "sale_price", "sold_at"]
        read_only_fields = ["id", "sold_at"]
