# Generated by Django 6.0.6 on 2026-06-17 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_WAREHOUSE', 'In Warehouse'), ('AT_HUB', 'At Hub'), ('SOLD', 'Sold')], default='IN_WAREHOUSE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.hub')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INGEST', 'Ingest'), ('TRANSFER', 'Transfer'), ('SALE', 'Sale')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bookitem')),
                ('from_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_movements', to='inventory.hub')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_movements', to='inventory.hub')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookitem',
            index=models.Index(fields=['serial_number'], name='inventory_b_serial__b7aa69_idx'),
        ),
        migrations.AddIndex(
            model_name='bookitem',
            index=models.Index(fields=['status'], name='inventory_b_status_3d7351_idx'),
        ),
        migrations.AddIndex(
            model_name='bookitem',
            index=models.Index(fields=['current_hub'], name='inventory_b_current_bf9f20_idx'),
        ),
    ]
