# Generated by Django 6.0.6 on 2026-06-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
