# Generated by Django 6.0.6 on 2026-07-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='current_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='inventory.hub'),
        ),
    ]
