# Generated by Django 6.0.6 on 2026-07-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bookitem_quantity_inventorymovement_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
